CREATE ROLE jean_jirard;
GRANT INSERT, SELECT, UPDATE ON ALL TABLES IN SCHEMA DEMO_DATA.PUBLIC to ROLE jean_jirard;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA DEMO_DATA.PUBLIC to ROLE jean_jirard;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA DEMO_DATA.PUBLIC to ROLE jean_jirard;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA DEMO_DATA.PUBLIC to ROLE jean_jirard;

CREATE OR REPLACE USER texas_ranger 
DISPLAY_NAME = 'texas ranger'
EMAIL = "shake-n-bake@rickybobby.com"
DEFAULT_WAREHOUSE = DEMO_DATA
DEFAULT_ROLE = jean_jirard
RSA_PUBLIC_KEY = "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7GOEeAO82K9jLCkdbmFm
jIt5ZK0zIGCcaXtys53KNAItC3/T8J/RlugTDwFIGrjiKrA1wFtwm2LI602QRd/G
Qoeiks4jyaRG2PZNvV/xbvMmDXIQhzmsLXp2cMe2dFMmgGWTS35QbeX4pM7JhpSG
/dXbWFOIb16DfmAeYXfi770hyTARsaqY7XLfeItYAIDfjKGz5ljiTHmlDTZP/4h6
doFdooD2J/4L3FCh465xuX8R0O78jO8WqxiMyAs/tbfpKD4XRFxVqfhS08u2Rm1g
44o6dynzD/E0O8CA4dhOxBIDSgmbFZsoAUu6s31qIUxT1HNai0/3m++WWPvjfrF5
kwIDAQAB"
