CREATE ROLE jean_jirard;
GRANT INSERT, SELECT, UPDATE ON ALL TABLES IN SCHEMA DEMO_DATA.PUBLIC to ROLE jean_jirard;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA DEMO_DATA.PUBLIC to ROLE jean_jirard;
GRANT USAGE ON ALL FUNCTIONS IN SCHEMA DEMO_DATA.PUBLIC to ROLE jean_jirard;
GRANT SELECT ON ALL MATERIALIZED VIEWS IN SCHEMA DEMO_DATA.PUBLIC to ROLE jean_jirard;

CREATE OR REPLACE USER texas_ranger 
DISPLAY_NAME = 'texas ranger'
EMAIL = "shake-n-bake@rickybobby.com"
DEFAULT_WAREHOUSE = DEMO_DATA
DEFAULT_ROLE = jean_jirard
RSA_PUBLIC_KEY = "A_public_key_goes_here"
